version: '3.1'

services:
  snippetbox:
    image: my-snippetbox
    build: .
    depends_on:
      - mysql
    ports:
      - "4000:4000"
    networks:
      - my_net
  mysql:
    image: my-mysql
    build:
      context: .
      dockerfile: Dockerfile-mysql
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_password
    secrets:
      - mysql_password
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - my_net
networks:
  my_net:
    driver: bridge
secrets:
  mysql_password:
    file: ./mysql_password.txt
volumes:
  mysql-data: